#!/usr/bin/env python
'''
Psyched is a scheduling and task management application.

Copyright 2007-2010 Eric Stein
License: GPL2/GPL3, at your option.  For details see LICENSE.
'''

PROGRAM 	= "Psyched"
PERIOD_3	= "_3D"
PERIOD_7	= "_W"
PERIOD_14	= "_2W"
HIDECAL		= "_Hide Cal"
SHOWCAL		= "_Calendar"
PREFS		= "Prefs"
SCHEDULE	= "Schedule"
TASKS		= "Tasks"
ATTENDED	= "Attended"
DATE		= "Date"
TIME		= "Time"
DURATION	= "Length"
TIMEDURATION	= "When / Length"
DONE		= "Done"
DESCRIPTION	= "Description"
IMPROPER	= " is improperly formatted."
DUPLICATE	= "Duplicate"
RESCHEDULE	= "Reschedule"
DELETE		= "Delete"
DUEDATE		= "Due Date"
DUETIME		= "Due Time"
NEWAPPOINTMENT	= "New Appointment"
NEWTASK		= "New Task"
OK		= "OK"
ERR_FORMATTING	= "Incorrect formatting."
CONFIG		= "Configure"
SETTING_PERS	= "Persistent window position"
SETTING_NT	= "Notify me about tasks"
SETTING_NS	= "Notify me about schedule items"
SETTING_NTD	= "Minutes before due"
SETTING_NSD	= "Minutes before appointment"
SETTING_SCT	= "Show Completed Tasks"
QUIT		= "Quit"
T_S		= "Task"
T_P		= "Tasks"
A_S		= "Appointment"
A_P		= "Appointments"
CONTINUE	= "Continue"
SIMILAR_T	= "This task may duplicate:"
CONFLICT	= "Conflict"
CONFLICT_T	= "This appointment conflicts with:"
CONFLICT_T_R	= "This new schedule conflicts with:"
PAST_T	 	= "Warning: scheduling a task for %d %s ago."
PAST_T_R 	= "Warning: rescheduling a task for %d %s ago."
PAST_S	 	= "Warning: scheduling an appointment for %d %s ago."
PAST_S_R 	= "Warning: rescheduling an appointment for %d %s ago."
